### ISSUE TITLE
AltPlugin incompatible with Mail 14.0

### ISSUE THREAD

**Issue by alberthenderson** [rileytestut/AltStore#612]
2 weeks ago everything work seamlessly without any issue.
Last week when I tried to refresh sideload app, and open up Mail App, it gave error Incompatible Plug-Ins Disabled for AltPlugin.mailbundle.
I've tried to uninstall and re-install back the Mail Plug-in and even uninstall and re-install the AltServer itself but still with no luck can't get rid of those error.
I've tried to follow this thread too [AltPlugin not compatible with Mail 14.0](https://github.com/rileytestut/AltStore/issues/443), and the error still exist.
Currently I'm running the latest AltServer 1.4.2 on MacOS Big Sur 11.1
does anyone experiencing the same issue?

**Comment by seezet** [comment]
I have a similar symptom, but it has not been resolved.
(Using Google Translate)

**Comment by thehappydinoa** [comment]
Having the same issue: 
![image](https://user-images.githubusercontent.com/30162978/103577520-f8c10580-4ea2-11eb-999a-3f32690ec947.png)

**Comment by 0-sss-yysuu-cckkkks-al00t-t** [comment]
why
why.
why.....
why...............

**Comment by 0-sss-yysuu-cckkkks-al00t-t** [comment]
WHY

**Comment by aquigni** [comment]
We need new UUID for Mail.app v14
<img width="928" alt="Screen Shot 2021-01-07 at 21 25 57" src="https://user-images.githubusercontent.com/6123352/103929990-1d311200-512f-11eb-99d4-b77638b29565.png">

**Comment by aquigni** [comment]
Just add to the end of Info.plist 

`<key>Supported11.2PluginCompatibilityUUIDs</key>
	<array>
		<string>D985F0E4-3BBC-4B95-BBA1-12056AC4A531</string>
	</array>`

and resign plugin in Terminal:

`sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle`

as it was solved in #443

**Comment by alberthenderson** [comment]
<img width="928" alt="info_plist" src="https://user-images.githubusercontent.com/63144084/104013738-76a74880-51e4-11eb-99d8-209f2c6e808f.png">

@aquigni I've tried with your solution, but the Incompatible Plug-ins error popup still exist

**Comment by Ben-Boardman** [comment]
@alberthenderson From what I've read, it appears it is because gatekeeper doesn't recognise the new .plist file you signed as a recognised developer. Until @rileytestut updates alt server, you'll have to disable gate keeper:
`sudo spctl --master-disable`

**Comment by alberthenderson** [comment]
@Ben-Boardman I've tried that too and set to "Anywhere" as one of the suggestion on [AltPlugin not compatible with Mail 14.0 #443](https://github.com/rileytestut/AltStore/issues/443), but error popup still make an apearance.

**Comment by CelticWebSolutions** [comment]
> @Ben-Boardman I've tried that too and set to "Anywhere" as one of the suggestion on [AltPlugin not compatible with Mail 14.0 #443](https://github.com/rileytestut/AltStore/issues/443), but error popup still make an apearance.

Just disable it from terminal with `sudo spctl --master-disable`

**Comment by Romntic** [comment]
same can any person add file after edite because I can't 

thanks

**Comment by bakedpotato191** [comment]
same, I've disabled gatekeeper yet the error still pops up.

**Comment by QuarterSwede** [comment]
I'm still having the same problem after updating to alt server 1.5b2 (44) which is supposed to fix the mail plugin issue. Looks like Riley added the code above to the Info.plist file. I also get the same issue with gatekeeper disabled. This is an odd one.

**Comment by bakedpotato191** [comment]
@QuarterSwede have you reinstalled the mail plugin?

**Comment by QuarterSwede** [comment]
Uninstalled, reinstalled, with SIP without SIP. Nothing works. It just says that the plug-in isn’t valid with Big Sur.

**Comment by bakedpotato191** [comment]
Yeah, same here.   
It seems like there are additional steps on the beta download page.

**Comment by QuarterSwede** [comment]
Even with all those extra steps it still refuses to work.

**Comment by mikigal** [comment]
> Just add to the end of Info.plist
> 
> ```
> <key>Supported11.2PluginCompatibilityUUIDs</key>
> <array>
> 	<string>D985F0E4-3BBC-4B95-BBA1-12056AC4A531</string>
> </array>
> ```
> 
> and resign plugin in Terminal:
> 
> `sudo codesign -f -s - /Library/Mail/Bundles/AltPlugin.mailbundle`
> 
> as it was solved in #443

Can you share way to get new UUID? It again stopped working since Monterey's Beta 6
