### ISSUE TITLE
Cannot Run on iOS 15.1 (19B5042h)

### ISSUE THREAD

**Issue by SmallKi-d** [rileytestut/AltStore#836]

**Comment by stormblizzard** [comment]
yes, flashed and crashed....

**Comment by blacksky2301** [comment]
same issues here !

**Comment by saleebm** [comment]
I had this issue, but I fixed it by going into Finder with the iPhone plugged in and clicking on the iPhone drive under locations. Then you just have to click "Trust this device" while your phone is connected and unlocked.

**Comment by spartandrew18** [comment]
Same here. Crashing on open.

**Comment by hsusanoo** [comment]
Same issue here. Attempting reinstall yields the following error:

![image](https://user-images.githubusercontent.com/35850056/134772456-b75e5371-b112-4c13-9255-37e148dc286c.png)

**Comment by pelmahx** [comment]
### **_iOS 15.1 beta, is not supported at this moment, wait for update (iOS 15 is supported)._**

**Comment by shanegillio** [comment]
hello, sorry for the lack of response - is the issue still occurring on the latest version?
